Repository f-lab-edu/play-your-color, pull requests merged in 2022-06, with the labels that each got.

#5 프로젝트 생성 및 모듈 구성
  .gitignore
  README.md
  build.gradle
  data/.gitignore
  data/build.gradle
  domain/.gitignore
  domain/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  local/.gitignore
  local/build.gradle
  local/consumer-rules.pro
  local/proguard-rules.pro
  local/src/androidTest/java/com/pyc/local/ExampleInstrumentedTest.kt
  local/src/main/AndroidManifest.xml
  local/src/test/java/com/pyc/local/ExampleUnitTest.kt
  presentation/.gitignore
  presentation/build.gradle
  presentation/proguard-rules.pro
  presentation/src/androidTest/java/com/pyc/playyourcolor/ExampleInstrumentedTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/pyc/playyourcolor/di/common/App.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/PlayListActivity.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/theme/Color.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/theme/Shape.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/theme/Theme.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/theme/Type.kt
  presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/ic_launcher_background.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
  presentation/src/main/res/xml/backup_rules.xml
  presentation/src/main/res/xml/data_extraction_rules.xml
  presentation/src/test/java/com/pyc/playyourcolor/ExampleUnitTest.kt
  settings.gradle
  test.kt
Labels: build

#8 상단 navigation tab 기본 구현
  build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/PlayListActivity.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/PlayListScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/colorplaylist/ColorPlayLIstScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/PlayListTabRow.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/primaryplaylist/PrimaryPlayListScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/settings/SettingsScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#11 Domain 데이터 모델 정의
  domain/src/main/java/pyc/domain/model/Audio.kt
  domain/src/main/java/pyc/domain/model/ColorInfo.kt
  domain/src/main/java/pyc/domain/model/ColorPlaylistItem.kt
Labels: feat

#15 ColorListInfo 및 ColorPlaylist DTO 클래스 수정
  local/src/main/java/com/pyc/local/dto/ColorListInfo.kt
  local/src/main/java/com/pyc/local/dto/ColorPlaylist.kt
Labels: fix
