Repository f-lab-edu/play-your-color, pull requests merged in 2022-07, with the labels that each got.

#19 PrimaryPlaylist와 ColorPlaylist DTO 클래스를 AudioPlaylist로 통합
  local/src/main/java/com/pyc/local/dto/AudioPlaylist.kt
  local/src/main/java/com/pyc/local/dto/PrimaryPlaylist.kt
Labels: fix

#13 기본 플레이리스트 관련 UseCase 작성
  build.gradle
  domain/build.gradle
  domain/src/main/java/pyc/domain/model/ColorPlaylistItem.kt
  domain/src/main/java/pyc/domain/model/PlaylistItem.kt
  domain/src/main/java/pyc/domain/repository/PlaylistRepository.kt
  domain/src/main/java/pyc/domain/usecase/DeletePrimaryAudioUseCase.kt
  domain/src/main/java/pyc/domain/usecase/GetPrimaryAudioListByColorUseCase.kt
  domain/src/main/java/pyc/domain/usecase/GetPrimaryAudioListUseCase.kt
  domain/src/main/java/pyc/domain/usecase/InsertPrimaryAudioUseCase.kt
  domain/src/main/java/pyc/domain/usecase/UpdatePrimaryAudioOrderUseCase.kt
Labels: feat

#24 기본플레이리스트&컬러플레이리스트 구현
  build.gradle
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/pyc/playyourcolor/extensions/AudioExts.kt
  presentation/src/main/java/com/pyc/playyourcolor/model/AudioModel.kt
  presentation/src/main/java/com/pyc/playyourcolor/model/AudioPlaylistItemModel.kt
  presentation/src/main/java/com/pyc/playyourcolor/model/ColorModel.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/PlayListActivity.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/colorplaylist/ColorPlayLIstScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/ButtonComponent.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/ColorListRow.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/PlaylistComponent.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/PlaylistFunctionBarRow.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/components/PlaylistScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/primaryplaylist/PrimaryPlayListScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/playlist/view/ui/theme/Color.kt
  presentation/src/main/res/drawable-anydpi/ic_action_more.xml
  presentation/src/main/res/drawable-hdpi/ic_action_more.png
  presentation/src/main/res/drawable-mdpi/ic_action_more.png
  presentation/src/main/res/drawable-xhdpi/ic_action_more.png
  presentation/src/main/res/drawable-xxhdpi/ic_action_more.png
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: feat, build

#29 GetSearchTitleOrArtistResultPlaylistUseCase 추가
  domain/src/main/java/pyc/domain/common/SearchlistUtils.kt
  domain/src/main/java/pyc/domain/model/PlaylistItem.kt
  domain/src/main/java/pyc/domain/usecase/SearchAudioByTitleOrArtistUseCase.kt
  gradle/wrapper/gradle-wrapper.properties
  presentation/src/test/java/pyc/domain/usecase/SearchAudioByTitleOrArtistUseCaseTest.kt
Labels: feat

#31 local에 PrefDatabase 구현
  local/src/main/java/com/pyc/local/di/PrefDatabaseModule.kt
  local/src/main/java/com/pyc/local/sharedpref/PrefDatabase.kt
  local/src/main/java/com/pyc/local/sharedpref/PrefDatabaseImpl.kt
Labels: feat

#34 drag and drop list 튕기는 현상 수정 및 편집 화면 컬러 정보 가져오기
  domain/src/main/java/pyc/domain/di/repository/FakePlaylistRepository.kt
  domain/src/main/java/pyc/domain/di/usecase/UseCaseModule.kt
  domain/src/main/java/pyc/domain/repository/PlaylistRepository.kt
  domain/src/main/java/pyc/domain/usecase/GetColorInfoUseCase.kt
  domain/src/main/java/pyc/domain/usecase/UpdateColorInfoUseCase.kt
  gradle/wrapper/gradle-wrapper.properties
  presentation/src/main/java/com/pyc/playyourcolor/common/ListExtensions.kt
  presentation/src/main/java/com/pyc/playyourcolor/editor/PlaylistEditorActivity.kt
  presentation/src/main/java/com/pyc/playyourcolor/editor/view/ui/PlaylistEditor.kt
  presentation/src/main/java/com/pyc/playyourcolor/editor/view/ui/components/DragDropList.kt
  presentation/src/main/java/com/pyc/playyourcolor/editor/view/ui/components/PlaylistEditorScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/editor/viewmodel/PlaylistEditorViewModel.kt
Labels: feat, fix

#44 오디오 파일 추가화면 ui
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/model/AudioFile.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/model/AudioFilePickerScreen.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/model/AudioFilePickerUiState.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/view/AudioFilePickerActivity.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/view/ui/component/AudioFilePickerList.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/view/ui/component/AudoiFilePicker.kt
  presentation/src/main/java/com/pyc/playyourcolor/audiofilepicker/viewmodel/AudioFilePickerViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#39 어플 종료 시점 플레이어 상태 관련 UseCase 정의
  data/src/main/java/com/pyc/data/datasource/LastPlayerStatusInformationDatasource.kt
  data/src/main/java/com/pyc/data/repository/LastPlayerStatusInformationRepositoryImpl.kt
  domain/src/main/java/pyc/domain/model/LastPlayerStatusInformation.kt
  domain/src/main/java/pyc/domain/repository/LastPlayerStatusInformationRepository.kt
  domain/src/main/java/pyc/domain/usecase/GetLastPlayerStatusInformationUseCase.kt
  domain/src/main/java/pyc/domain/usecase/SaveLastPlayerStatusInformationUseCase.kt
  local/build.gradle
  local/src/main/java/com/pyc/local/datasource/LastPlayerStatusInformationDatasourceImpl.kt
Labels: feat, build

#42 PrefDatabase 저장 데이터 중 currentPlayingItemId -> currentPlayingItemPosition으로 변경
  data/src/main/java/com/pyc/data/datasource/LastPlayerStatusInformationDatasource.kt
  data/src/main/java/com/pyc/data/repository/LastPlayerStatusInformationRepositoryImpl.kt
  domain/src/main/java/pyc/domain/repository/LastPlayerStatusInformationRepository.kt
  local/src/main/java/com/pyc/local/datasource/LastPlayerStatusInformationDatasourceImpl.kt
  local/src/main/java/com/pyc/local/sharedpref/PrefDatabase.kt
  local/src/main/java/com/pyc/local/sharedpref/PrefDatabaseImpl.kt
  local/src/test/java/com/pyc/local/datasource/LastPlayerStatusInformationDatasourceImplTest.kt
Labels: fix

#47 LastPlayerStatusInformationDatasourceImpl 클래스 수정
  local/src/main/java/com/pyc/local/datasource/LastPlayerStatusInformationDatasourceImpl.kt
Labels: fix
